### ISSUE TITLE
Stereocamera to 3D model

### ISSUE THREAD

**Issue by naveen-mukkatt** [RoboSub-UTD/MATE2024#8]
## Tasks:

- [ ] Define workflow.
- [ ] Ensure ZED camera is working and publishing to ROS topic.
- [ ] Convert camera feed into point-cloud.
- [ ] Convert point-cloud into mesh.
- [ ] Turn mesh into 3D model.
